<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Produk</name>
   <tag></tag>
   <elementGuidId>468dbeea-7664-4a5c-93e0-fea62b5d120e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nm_produk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nm_produk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a34f3ca7-78b7-4e6b-bb6d-f56239e69cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>240771d8-3821-4d30-95f2-894c6f8182a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f9016463-45a9-4da9-af04-be6af227ba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nm_produk</value>
      <webElementGuid>fb5e0a91-a6d8-46f8-b6d4-42f48dafab89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Produk</value>
      <webElementGuid>2e8833c0-ee6a-4601-9189-3482c58fa9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nm_produk&quot;)</value>
      <webElementGuid>ca50db53-37ce-4f80-a416-f1ae55fdc90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nm_produk']</value>
      <webElementGuid>10887e5d-d853-4ba9-bc82-b17f851598ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/input</value>
      <webElementGuid>8004bd19-2570-45da-82ea-535980e21fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>87b8c115-42d7-484e-8a46-d317cf2d74c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'type' and @id = 'nm_produk' and @placeholder = 'Nama Produk']</value>
      <webElementGuid>f5145738-e879-4678-a6f1-7acec15f4ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
